server:
  port: 8000

spring:
  application:
    name: hoc-hoa-free
  datasource:
    url: jdbc:mysql://localhost:3306/abet_cse
    username: root
    password: 
    driverClassName: com.mysql.cj.jdbc.Driver
    hikari:
      maximumPoolSize: 10
  api:
    base:
      url: https://abet.apimatic.dev/v/1_0#/http/api-endpoints/
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  thymeleaf:
    prefix: classpath:/resources/
  servlet:
    multipart:
      maxFileSize: 30MB
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp

jwt:
  secret: mS90Jysm4r9jRFiIT3mi1rDSCCvQH0v8R7PcyBqwR1p6
  expirationInHour: 24
